### PR TITLE
Add Replicate demo and API

### PR DESCRIPTION
**Pull request by chenxwh**
Hi @LeoXing1996,

Happy new year!

This pull request makes it possible to run `PIA` on Replicate (https://replicate.com/cjwbw/pia) and via API (https://replicate.com/cjwbw/pia/api). Also happy to transfer the demo page to `open-mmlab` so you can make modifications easily :)

### CODE REVIEW

**Comment by LeoXing1996** [comment]
Hey @chenxwh, happy new year!
Thank your for your contribution to support online demo on Replicate!  I have two small comments regarding this PR:

1. The new added config are located under the `example/openxlab` folder, Would it be more appropriate to name the folder as `example/replicate`?
3. Additionally, it would be great if you could include your modifications in the "What's New" section as well.

**Comment by chenxwh** [comment]
Hi @LeoXing1996,

Sure, I have just made the changes! Let me know if you like me to transfer the ownership of the demo to `open-mmlab` :)

**Comment by LeoXing1996** [comment]
Thanks for your effort, this PR is good enough to merge!

Regarding the demo you mentioned for OpenMMLab, are you referring to the demo in this [link](https://openxlab.org.cn/apps/detail/zhangyiming/PiaPia)? If so, unfortunately, I cannot transfer ownership to you as I am using my private repo to maintain this demo. If you have any suggestion, you can create a issue or discuss in this PR, and I will try to support them as soon as possible.

**Comment by LeoXing1996** [comment]
Thanks for your effort, this PR is good enough to merge!

Regarding transferring ownership to `open-mmlab`, do you mean creating an official account of `open-mmlab` on Replicate and then transfer the ownership to that account?

**Comment by chenxwh** [comment]
yes! I have created the page here https://replicate.com/open-mmlab, if you sign-in on replicate with your github usrname, then I can add you under the `open-mmlab` organisation, which gives you the authorisation to modify the demo, push for new updates, edit examples etc :)

**Comment by LeoXing1996** [comment]
@chenxwh, sorry for late response. 
Thank you for creating an account for openmmlab and the corresponding PIA demo. I just registered with my GitHub username on replicate, and you can add me to the corresponding organization. 
However, I have a question: How should I manage the replicate account for openmmlab?

**Pull request merged**
